#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

until [[ -f "${__dir}/postgres.is_ready" ]]
do
    echo "Waiting for postgres.."
    sleep 5
done

exec "${@}"
